PesaCrow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('home/', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('projects/', include('projects.urls')),
    path('contracts/', include('contracts.urls')),
    path('payment/', include('payment.urls')),
    path('deliverables/', include('deliverables.urls')),
    path('disputes/', include('disputes.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),    
]

contracts/urls.py
from django.urls import path
from . import views

app_name = "contracts"

urlpatterns = [
    path('', views.contract, name='contract'),
    path('edit_contract/<int:contract_id>/', views.edit_contract, name='edit_contract'),
    path('review_contract/<int:contract_id>/', views.review_contract, name='review_contract'),
    path('view_contract/<int:contract_id>/', views.view_contract, name='view_contract'),
    path('download_contract_pdf/<int:contract_id>/', views.download_contract_pdf, name='download_contract_pdf'),
]

disputes/urls.py
from django.urls import path
from . import views

app_name = 'disputes'

urlpatterns = [

    path('disputes_list/', views.disputes_list, name="disputes_list"),
    path('raise_dispute/<int:dispute_id>/', views.raise_dispute, name="raise_dispute"),
    path('disputes/resolve_dispute/<int:dispute_id>/', views.resolve_dispute, name="resolve_dispute"),
    path('<int:dispute_id>/escalate/manual/', views.escalate_dispute_manually, name='escalate_dispute_manually'),
    path('dispute/<int:dispute_id>/', views.dispute_detail, name="dispute_detail"),


]

home/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import dashboard_view

# from .views import DashboardView

app_name = "home"
urlpatterns = [
    path('admin-dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('', views.homepage, name='home'),
    path('login/', views.login_page, name="login"),
    path("logout/", views.logoutPage, name="logout"),

    path('register/', views.RegistrationView.as_view(), name='register'),

    path('login/password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('admin-disputes/', views.admin_disputes, name='admin_disputes'),

    # path('dashboard/project_detail<int:id>' views.d)


]

profiles/urls.py
from django.urls import path
from profiles import views

app_name = "profiles"

urlpatterns = [
    path('', views.profiles, name='profile'),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = "projects"

urlpatterns = [
    path('client/projects/', views.projectrequest, name="projectrequest"),

    path('developer/projects/', views.developers_projects, name="developers_projects"),  # Developers see project requests
    
    path('developer/projects/accept/<int:project_id>/', views.accept_project, name="accept_project"),# Accept project request

    path('developer/projects/milestones/<int:project_id>/', views.create_milestones, name="milestones"),

    path("developer/projects/milestones/<int:milestone_id>/edit/", views.edit_milestone, name="edit_milestone"),

    path("milestones/<int:id>/", views.client_milestone_verification, name="client_verify_milestone"),

    ]

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PesaCrow</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
    <script
      src="https://unpkg.com/htmx.org@2.0.4"
      integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+"
      crossorigin="anonymous"
    ></script>
    {% tailwind_css %}
  </head>
  <body class="font-custom">
    {% block navbar %}

    {% endblock %} {% block sidebar %} {% endblock %} {%block content %} {% endblock %} {% block footer %} {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/41.1.0/classic/ckeditor.js"></script>
  </body>
</html>

templates/footer.html
{% extends "base.html" %}

{% block footer %}
<footer class="bg-white shadow-sm dark:bg-gray-900">
    <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <div class="sm:flex sm:items-center sm:justify-between">
            <a href="#" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="PesaCrow logo" />
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">PesaCrow</span>
            </a>
            <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0 dark:text-gray-400">
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">About</a>
                </li>
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">Privacy Policy</a>
                </li>
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">Licensing</a>
                </li>
                <li>
                    <a href="#" class="hover:underline">Contact</a>
                </li>
            </ul>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
        <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2025 <a href="#" class="hover:underline">PesaCrow™</a>. All Rights Reserved.</span>
    </div>
</footer>
{% endblock %}

templates/navbar.html
{% extends "base.html" %}

{% block navbar %}
<nav class="bg-white border-gray-200 dark:bg-customBlue">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
        <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">PesaCrow</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
{#            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>#}
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-customBlue md:dark:bg-customBlue dark:border-customBlue">
        <li>
          <a href="{% url 'home:home' %}" class="block py-2 px-3 text-white bg-blue-700 rounded-sm md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" aria-current="page">Home</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Services</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
        </li>
        <li>
          <a href="{% url 'home:login' %}" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Login</a>
        </li>
        <li>
          <a href="{% url 'home:register' %}" class="block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Register</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

templates/sidebar.html
{% extends "base.html" %} {% block sidebar %}
<button
  data-drawer-target="default-sidebar"
  data-drawer-toggle="default-sidebar"
  aria-controls="default-sidebar"
  type="button"
  class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
>
  <span class="sr-only">Open sidebar</span>
  <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="48" height="48" style="shape-rendering:geometricPrecision;text-rendering:geometricPrecision;image-rendering:optimizeQuality;fill-rule:evenodd;clip-rule:evenodd"><defs><style>.fil2{fill:none}.fil0{fill:#006064}.fil3{fill:#ff8a65}</style></defs><g id="Layer_x0020_1"><path class="fil0" d="M1647.83 448.082H399.87c-79.199 0-143.875 64.676-143.875 143.858v624.14c0 79.438 64.676 143.858 143.875 143.858h1247.96c79.438 0 144.164-64.42 144.164-143.858V591.94c0-79.182-64.727-143.858-144.164-143.858z"/><path d="M1647.83 488.081H399.87c-8.019 0-15.834.92-23.343 2.663l-.774.19 1357.88 783.97.056-.08c11.533-16.703 18.305-36.933 18.305-58.744V591.94c0-57.265-46.972-103.86-104.165-103.86zm-1272.07 2.854c-45.59 10.95-79.759 52.188-79.759 101.006v624.14c0 57.248 46.644 103.859 103.876 103.859h1247.96c35.5 0 66.978-17.828 85.804-45.035L375.76 490.935z" style="fill:#e1f5fe"/><path class="fil2" d="M0 0h2048v2048H0z"/><path class="fil2" d="M255.999 255.999h1536v1536h-1536z"/><path class="fil2" d="M255.999 255.999h1536v1536h-1536z"/><path class="fil0" d="M1719.77 1392.14h-503.853c0 14.69-21.53 26.679-48.044 26.679H879.834c-26.462 0-47.754-11.99-47.754-26.679H327.938c-39.608 0-71.938 17.815-71.938 39.933 0 22.11 32.33 39.925 71.938 39.925h1391.83c39.83 0 72.227-17.815 72.227-39.925 0-22.118-32.398-39.933-72.227-39.933z"/><g id="_347130072"><path id="_347131872" class="fil3" d="M470.385 668.672H1577.61v54.676H470.385z"/><path id="_347132064" style="fill:#ff7043" d="M470.385 876.673H1577.61v54.675H470.385z"/><path id="_347130264" class="fil3" d="M470.385 1084.67H1577.61v54.68H470.385z"/></g></g></svg>
</button>

<aside
  id="default-sidebar"
  class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
  aria-label="Sidebar"
>
  <div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
    <ul class="space-y-2 font-medium">
      <li>
        <a
          href="{% url 'home:dashboard' %}"
          class="flex items-center mt-32 p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
        <svg
            class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 18 18"
          >
            <path
              d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"
            />
          </svg>
          <span class="ms-3">Dashboard</span>
        </a>
      </li>
      <li>
        <a
          href="{% url 'projects:projectrequest' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
        <svg class=" shrink-0 w-5 h-5 text-gray-500" 
        id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><defs><style>.cls-1{fill-rule:evenodd}</style></defs><path d="M37.8 46.5H10.2a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1h7.4a1 1 0 0 1 0 2h-6.4v34.5h25.6V10h-6.4a1 1 0 1 1 0-2h7.4a1 1 0 0 1 1 1v36.5a1 1 0 0 1-1 1z"/><path class="cls-1" d="M16 19.59a1.6 1.6 0 1 1-1.6 1.6 1.6 1.6 0 0 1 1.6-1.6z"/><path d="M33.58 22.19h-13.7a1 1 0 0 1 0-2h13.7a1 1 0 0 1 0 2z"/><path class="cls-1" d="M16 26.6a1.6 1.6 0 1 1-1.6 1.6 1.6 1.6 0 0 1 1.6-1.6z"/><path d="M33.58 29.2h-13.7a1 1 0 0 1 0-2h13.7a1 1 0 0 1 0 2z"/><path class="cls-1" d="M16 33.6a1.6 1.6 0 1 1-1.6 1.6 1.6 1.6 0 0 1 1.6-1.6z"/><path d="M33.58 36.2h-13.7a1 1 0 1 1 0-2h13.7a1 1 0 0 1 0 2zM30.4 13.37H17.6a1 1 0 0 1-1-1v-6.5a1 1 0 0 1 1-1h3.06V4.2a2.7 2.7 0 0 1 2.7-2.7h1.28a2.69 2.69 0 0 1 2.69 2.7v.67h3.07a1 1 0 0 1 1 1v6.5a1 1 0 0 1-1 1zm-11.8-2h10.8v-4.5h-3.07a1 1 0 0 1-1-1V4.2a.7.7 0 0 0-.69-.7h-1.28a.71.71 0 0 0-.7.7v1.67a1 1 0 0 1-1 1H18.6z"/></svg>

          <span class="flex-1 ms-3 whitespace-nowrap">Projects</span>
          <span
            class="inline-flex items-center justify-center px-2 ms-3 text-sm font-medium text-gray-800 bg-gray-100 rounded-full dark:bg-gray-700 dark:text-gray-300"
          ></span>
        </a>
      </li>
      <li>
        <a
          href="{% url 'deliverables:deliverable_list' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 18 18"
          >
            <path
              d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Deliverables</span>
          <span
            class="inline-flex items-center justify-center px-2 ms-3 text-sm font-medium text-gray-800 bg-gray-100 rounded-full dark:bg-gray-700 dark:text-gray-300"
          ></span>
        </a>
      </li>
      <li>
        <a
          href="{% url 'contracts:contract' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
          <svg
            class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="currentColor"
            viewBox="0 0 20 20"
          >
            <path
              d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"
            />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Contracts</span>
          <span
            class="inline-flex items-center justify-center w-3 h-3 p-3 ms-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300"
            ></span
          >
        </a>
      </li>
      <li>
        <a
          href="{% url 'disputes:disputes_list' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
        <svg
        class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        viewBox="0 0 18 18"
      >
        <path
          d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"
        />
      </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Disputes</span>
        </a>
      </li>
      <li>
        <a
          href="{% url 'profiles:profile' %}"
          class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
        <svg
        class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        viewBox="0 0 20 18"
      >
        <path
          d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"
        />
      </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Profiles</span>
        </a>
      </li>
      <li>
        <a
          href="{% url 'home:logout' %}"
          class="flex items-center mt-64 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group"
        >
        <svg
        class="shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white"
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 18 16"
      >
        <path
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"
        />
      </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Logout</span>
        </a>
      </li>
    </ul>
  </div>
</aside>
{% endblock %}